[build-system]
requires = ["setuptools>=61", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "depthcrafter"
description = "[CVPR 2025 Highlight] DepthCrafter: Generating Consistent Long Depth Sequences for Open-world Videos"
dynamic = ["version"]
dependencies = [
    "accelerate",
    "decord",
    "diffusers",
    "numpy",
    "matplotlib",
    "mediapy",
    "Pillow",
    "torch",
    "transformers"
]

[tool.setuptools.packages.find]
include = ["depthcrafter*"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[project.urls]
Repository = "https://github.com/samaust/DepthCrafter"
